# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
- master

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.Name):nightly'
  dockerHubID: 'kunaltyagi'

stages:
- stage: FasterClang
  displayName: 'Build docker with a faster clang'
  jobs:  
  - job: clang
    timeoutInMinutes: 360
    displayName: 'Build Clang w/ LTO'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build clang w/ LTO docker image'
      inputs:
        command: build
        dockerfile: 'clang/Dockerfile'
        repository: $(dockerHubID)
        tags: $(tag)
    - task: Docker@2
      displayName: 'Push clang w/LTO image'
      inputs:
        command: push
        containerRegistry: $(dockerHub)
        repository: $(dockerHubID)
        tags: $(tag)
